### ISSUE TITLE
Bug: Unshared snippets are still viewable by others

### ISSUE THREAD

**Issue by nikihaj** [Kholid060/snapcode#10]
When I share a snippet, I can share the generated link with others so they can see the snippet. But if I turned off sharing for that snippet, other people can still see the snippet. 

Expected behaviour: When you unshare a snippet, the link should become invalidated.

**Comment by Kholid060** [comment]
I have fixed this at d81a740f9af1a338ff3f0e3bd33b58a1b9ef8613
