### ISSUE TITLE
Firebase integration

### ISSUE THREAD

**Issue by 262media** [Kholid060/snapcode#11]
I'm having issues with the lack of instructions for the firebase integration

`main.js:239 Uncaught (in promise) Error: In order to use an Identity provider, you should initiate the "Auth" instance with a "redirectUri".
    at o.signInWithProvider (main.js:239)
    at Proxy.r (AuthModal.vue:37)
    at AuthModal.vue:16
    at Kt (runtime-core.esm-bundler.js:154)
    at Dt (runtime-core.esm-bundler.js:163)
    at HTMLButtonElement.n (runtime-dom.esm-bundler.js:292)`

**Comment by Kholid060** [comment]
Have you added the `redirectUri` property when you initiate the Auth instance? If you have added it, your code should look like this:
```js
// utils/firebase.js
import Auth from 'firebase-auth-lite';

export const auth = new Auth({
  apiKey: process.env.VUE_APP_FIREBASE_API_KEY,
  redirectUri: process.env.VUE_APP_REDIRECT_URI,
});
```
For firebase auth integration, I'm using [firebase-auth-lite](https://github.com/samuelgozi/firebase-auth-lite) and you see the documentation there.

**Comment by 262media** [comment]
I'm adding those to a .env file the  VUE_APP_REDIRECT_URI='https://mywebsite.com/auth' is this correct? thank you

**Comment by Kholid060** [comment]
Yes, it's correct
