### ISSUE TITLE
Possibly change from Highlight.js to Prism.js

### ISSUE THREAD

**Issue by denno020** [Kholid060/snapcode#12]
**Is your feature request related to a problem? Please describe.**
Currently Snapcode doesn't like React code, specifically JSX within React code. This is a limitation of highlight.js. Looking through issues on that projects Github, someone has suggested Prism.js, as it does support JSX, as well as a tonne more languages.

**Describe the solution you'd like**
Investigate if changing from Highlight.js to Prism.js is something that Snapcode might benefit from

**Describe alternatives you've considered**
Sticking with Highlight.js, that doesn't support React/JSX, cuts off a lot of developers from potentially using the platform to store snippets/code.

**Comment by Kholid060** [comment]
Hi @denno020, I have added JSX support(fc5f3827f7e301310e0cf80701a6ef0bdf58f940), now you can write react code in snapcode.  And I'm using codemirror for the code highlighter not highlight.js

**Comment by denno020** [comment]
Oh great! Thanks.

Ah right, sorry! The PR titled `Bump highlight.js from 9.18.1 to 9.18.5` threw me 😅
