### ISSUE TITLE
Authentication option

### ISSUE THREAD

**Issue by MohamedElashri** [Kholid060/snapcode#121]
**Is your feature request related to a problem? Please describe.**
Anybody can access the snippets which is not good from security and privacy perspective

**Describe the solution you'd like**
A auth system that can be simple but put the snippets after some password gate

**Describe alternatives you've considered**
One option is that you can use reverse proxy auth, but it is not very efficient. 

**Additional context**

**Comment by Kholid060** [comment]
Can you elaborate more on the feature that you request? Because as far as I know, only you that can access the snippet unless you share your snippet.

**Comment by MohamedElashri** [comment]
> Can you elaborate more on the feature that you request? Because as far as I know, only you that can access the snippet unless you share your snippet.

This was my problem in describing,  I mean that once you deploy this on public internet then anyone can use it once they know the url. What I propose is someway of limiting access to particular people

**Comment by Kholid060** [comment]
I think I'll add password protection for a snippet in the next update

**Comment by Kholid060** [comment]
Password protection has been added to the Snapcode v2.3.0 (b49a594ea7383169a64c648bb9694edd6bb758ab)
