### ISSUE TITLE
Copy button is not working..

### ISSUE THREAD

**Issue by GraphicOwls** [Kholid060/snapcode#13]
The `copy` button to copy the code is not working on **shareable links**. It works when I am viewing my own code, but as soon as I share it with the generated link, the person receiving it cannot copy the code with the `copy` button.

**Comment by Kholid060** [comment]
Hi, I've fixed this issue (602cf4d9b88004d848130e4811697876e3cbc138)

**Comment by GraphicOwls** [comment]
Thanks so much! 👍🏻
