### ISSUE TITLE
Python language support

### ISSUE THREAD

**Issue by gitzain** [Kholid060/snapcode#14]
**Is your feature request related to a problem? Please describe.**
I cannot tag my code snippet as a "python" code snippet.

**Describe the solution you'd like**
Please add python support.

**Describe alternatives you've considered**
I've tried using another language tag but i dont have the option to select "none".

**Additional context**
N/A

Keep up the great work.

**Comment by Kholid060** [comment]
Hi, snapcode is now support python language (ef06dbd70fa80797847ea4b4dd356f9ca07855d8)
