### ISSUE TITLE
🤯 Visual Studio Code Extension

### ISSUE THREAD

**Issue by eggsy** [Kholid060/snapcode#16]
**Is your feature request related to a problem? Please describe.**
It's a feature request.

**Describe the solution you'd like**
It'd be amazing if you could make a Visual Studio Code extension to upload the selected part of our code to your API. I don't think it'd be that hard to do since you have the API running and you did a great job building the whole system...

**Describe alternatives you've considered**
I use other extensions but they all export as PNG files, which could also be an option for your extension but I'd prefer a cool webpage like yours current situation.

**Additional context**
None.

**Comment by zardoy** [comment]
Why did you close this one? I'd like to make integration with your service in [my extension](https://t.co/X3rJKz68o0). I think it'd extremely handy!
