### ISSUE TITLE
[BUG] CORS issue on the `.vercel.app` domain

### ISSUE THREAD

**Issue by eggsy** [Kholid060/snapcode#18]
**Describe the bug**
Looks like you have moved from Heroku to Vercel, but during your requests to your Heroku app, it fails on (my) and some other friends' browsers due to CORS error. You should probably fix this from Heroku side or move your API to the same domain.

**To Reproduce**
1. Go to a snippet link ([example](https://snapcode.vercel.app/snippet/XHNqS5f5zkogMCh5Apt4i))
2. Wait until it tries to fetch the content
3. See error, it will display a 404 error

**Expected behavior**
Should fetch the content successfully and display it.

**Screenshots**

![image](https://i.vgy.me/entshE.png)
![image](https://user-images.githubusercontent.com/13917975/114934514-a5b40280-9e42-11eb-819b-bbe17522c553.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 87.0

**Comment by Kholid060** [comment]
Hi, I've fixed this CORS issue
