### ISSUE TITLE
All my Snippets are Gone & the Page Links

### ISSUE THREAD

**Issue by GraphicOwls** [Kholid060/snapcode#401]
**Describe the bug**

**To Reproduce**
Just logged in and everything is gone. I had tons of snippets, organized in folders and snippets that were being shared with people as well. Now links are broken and everything is gone.

**Expected behavior**
Being able to log in and see all my folders and snippets. Now everything has just vanished.

**Screenshots**
Here is a screenshot, showing one of my snippets being shared via public link, and the user below saying page doesn't exist.

<img width="655" alt="CleanShot 2022-12-14 at 11 37 57@2x" src="https://user-images.githubusercontent.com/30763670/207654509-70b1c64b-1bab-487b-a3b3-b4c9d30464d9.png">

It used to be here: https://snapcode.vercel.app/snippet/6MJePaXH0HkaukvxV_djJ

I never deleted anything myself.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: Macbook Pro Max — Apple M1 Max
 - OS: MacOS Ventura — 13.1
 - Browser: Arc — Version 0.80.0
 - Chromium Engine Version 108.0.5359.99

**Additional context**
![CleanShot 2022-12-14 at 11 42 38@2x](https://user-images.githubusercontent.com/30763670/207655548-a7260786-5ed4-46b0-bd70-300114656e3c.png)

![CleanShot 2022-12-14 at 11 43 13@2x](https://user-images.githubusercontent.com/30763670/207655683-dc047f89-cf6b-4ed2-a902-fdaef36cc015.png)

**Comment by Kholid060** [comment]
Sorry for the inconvenience you have experienced, Snapcode currently not working due to the deletion of the server on [Heroku](https://help.heroku.com/RSBRUH58/removal-of-heroku-free-product-plans-faq). I'll migrate it as soon as possible.

**Comment by GraphicOwls** [comment]
Ah ok. Thanks for the info. Did that happen when Heroku was hacked? Also, when you migrate, do you think all the snippets will come back?

**Comment by Kholid060** [comment]
All the snippets will come back once the server is come back
