### ISSUE TITLE
starred snippets and folders created don't survive logouts

### ISSUE THREAD

**Issue by adhanji8** [Kholid060/snapcode#8]
When you create starred snippets or folders, and then logout, when you log back in, those stars and folders are not persisted. Amazing project by the way, great work!

**Comment by Kholid060** [comment]
Hi, thanks for opening an issue. I have fixed this bug a3602d571d4d31348e712b41261541886d783272, now you can logout and log back in without losing your new folders. And before you log out, don't forget to click the backup button. If you have further question you can reply here

**Comment by adhanji8** [comment]
Thank you so much. Currently the data is stored locally within the browser right? So if we wanted it to stay in sync across different machines we would need to add some code to allow for saving it to a database and creating the association with the logged in user.

**Comment by Kholid060** [comment]
Yes, but you don't actually need to add some code to the snippet first. You just need to click the backup button at the top right when you add/update/delete a snippet or folder, and it will save it to the database and it will sync it across the different machines you use (when you login using the same account of course).

**Comment by Kholid060** [comment]
In the next update, I will add a timer so you don't need to click the backup button whenever data is changed
